group=black
name=mount
#full service name here would be black.mount
description='cool stuff'
exec=/bin/mount #path to executable
after=black.x,group[y] #what services should be run before this server, in this case black.x and all services of group "y"