group=black
name=mount
#full service name here would be black.mount
description='cool stuff'
exec=/bin/mount #path to executable
after=group[y] #what group services should be run before this server, in this case all services of group "y" (DOES NOT SUPPORT SINGEL SERVICES YET)